name: "Rollback GitHub Publish"
author: "Kungfu Trader"
description: "Rollback GitHub packages publish"
inputs:
  token:
    description: "E.g. secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
